### PR TITLE
Enforce order for mixin

### LINKED ISSUE #14: Enforce declarations order with stylelint
Initially mentioned in https://github.com/wagtail/wagtail/issues/5246#issuecomment-485861248, and discussed again in a UI team meeting.

We want to use [stylelint-order](https://github.com/hudochenkov/stylelint-order) for this, we want to enforce mixins are first in declarations, and I think that’s about it.

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
I have enforced mixins as first in declarations. Fixes #14

### CODE REVIEW

**Comment by PaarthAgarwal** [comment]
I really need to learn how to use prettier😅

**Comment by lb-** [comment]
@PaarthAgarwal what editor do you use? happy to help you get your prettier set up.

As for this PR - can you please add a 'passing' example to the valid.scss https://github.com/wagtail/stylelint-config-wagtail/blob/main/__tests__/scss-valid.scss


and a failing example to the invalid scss https://github.com/wagtail/stylelint-config-wagtail/blob/main/__tests__/scss-invalid.scss

We are not currently too strict on unit tests in this repo but in this case it is an easy thing to add and also ensures there is a visual reference in the PR of what we are blocking/allowing.

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal what editor do you use? happy to help you get your prettier set up.
> 
I appreciate your help. Currently I am using VS Code
> As for this PR - can you please add a 'passing' example to the valid.scss https://github.com/wagtail/stylelint-config-wagtail/blob/main/__tests__/scss-valid.scss
> 
> and a failing example to the invalid scss https://github.com/wagtail/stylelint-config-wagtail/blob/main/__tests__/scss-invalid.scss
> 
> We are not currently too strict on unit tests in this repo but in this case it is an easy thing to add and also ensures there is a visual reference in the PR of what we are blocking/allowing.

Sure I'll add them right now

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal what editor do you use? happy to help you get your prettier set up.
> 
> As for this PR - can you please add a 'passing' example to the valid.scss https://github.com/wagtail/stylelint-config-wagtail/blob/main/__tests__/scss-valid.scss
> 
Since we just enforced order of mixins I have moved @mixin to top in valid.css.

> and a failing example to the invalid scss https://github.com/wagtail/stylelint-config-wagtail/blob/main/__tests__/scss-invalid.scss
> 
Here @mixin was already not at the top so I feel this should be valid enough for the invalid.css to be invalid (or invalid enough for the invalid.css to be valid)

> We are not currently too strict on unit tests in this repo but in this case it is an easy thing to add and also ensures there is a visual reference in the PR of what we are blocking/allowing.

Let me know if I should add separate code for them or this approach will work.

**Comment by PaarthAgarwal** [comment]
Linting issues are fixed but some errors are coming because of valid.css. Tried a few fixes but stuck.
Need help

**Comment by lb-** [comment]
OK this was a bit tricky, the issue was that when the tests fail they fail inside a promise, the simplest way around this when working locally is via logging.

Once logging was added it looks like the usage of `unspecified` was incorrect, I have instead changed this to 'declarations' as this seems to cover the use case fine.

Finally, there was some confusion I think the requirement was actually for the usage of mixins (via `include`) not the declaration of mixins (via `@mixin`).

I have pushed to your branch and will merge in shortly.

Thanks for this @PaarthAgarwal

**Pull request merged**
